### ISSUE TITLE
Local language loading problem

### ISSUE THREAD

**Issue by Steyfix** [The-Cataclysm-Preservation-Project/TrinityCore#315] opened 2022-01-07 16:15 UTC
Hello as mentioned on the discord, after selecting the frFR language for my server I found a problem in the loading of local table data. It does not charge them while the frFR value at the local quest level is full.
<a href="https://zupimages.net/viewer.php?id=22/01/3uz6.png"><img src="https://zupimages.net/up/22/01/3uz6.png" alt="" /></a>

<a href="https://zupimages.net/viewer.php?id=22/01/2909.png"><img src="https://zupimages.net/up/22/01/2909.png" alt="" /></a>

**Comment by funjoker** [comment] 2022-01-07 17:39
The stuff displayed ingame is determined by the client locale on connect. The realmzone does not affect the language displayed ingame.

Intertesting is, that some objectives are localized. I guess here the problem is inside compltetionTexts.

**Comment by funjoker** [comment] 2022-01-07 18:49
Quest ID is not 790.
Quest ID is 25129.

Checked inside DB.
There is no locale for this quest inside DB.

**Comment by Steyfix** [comment] 2022-01-07 19:15
I confirm that by changing the id of the local quest by the id 25129 that I add the local frFR suddenly there is a concern of id location for the quests

**Closed** 2022-01-08 21:22 UTC
Labels: Database

**Comment by Ovahlord** [comment] 2022-01-08 21:27
clearing cache is recommended. you know the drill.

**Comment by Steyfix** [comment] 2022-01-09 07:05
hey my cache is emptied at each start with my launcher
