### ISSUE TITLE
Show Cloak / Helm reset on relog

### ISSUE THREAD

**Issue by lingxDEV** [The-Cataclysm-Preservation-Project/TrinityCore#205] opened 2021-01-05 00:36 UTC
**Description:**

Show Cloak / Helm is bugged

**Current behaviour:**

When you hide cloak or helm in Interface > Display, it will display again on relog.

**Expected behaviour:**

It should stay hidden.

**Steps to reproduce the problem:**

https://streamable.com/wyb2hf

**TC rev. hash/commit:** 

5c0febcfb38828a28da9edd27900a85e052cc738

**TDB version:** 

TDB 434.20091

**Operating system:** 

Win10 64

**Comment by TranceAccount** [comment] 2021-01-05 09:29
Duplicate of #94

**Closed** 2021-01-05 09:42 UTC
