### ISSUE TITLE
Bnetserver.exe ... Cannot Connect to Realm...

### ISSUE THREAD

**Issue by DickFiddler** [The-Cataclysm-Preservation-Project/TrinityCore#29] opened 2020-02-04 18:16 UTC
**Description:**

Bnetserver.exe ... Client cannot connect to realm...

**Current behaviour:**

434 client fails to connect to bnetserver ... however same client can see 335a authserver.

**Expected behaviour:**

Should see realmlist in client

**Steps to reproduce the problem:**

1. Pull and compile TCPP...  
2. Patch Wow.exe
3. Try and connect

**TC rev. hash/commit:** 

TrinityCore rev. 2ad22015ad45+ 2020-02-03 08:37:38 +0100 (master branch) (Win64, Debug, Static) (bnetserver)

**TDB version:**  Using World DB: TDB 434.34

**Operating system:** Fatdog Linux 64 / wine64.

uname -a
Linux zap64 4.14.12 #1 SMP Tue Jan 9 23:44:49 AEST 2018 x86_64 AMD Athlon(tm) II X2 215 Processor AuthenticAMD GNU/Linux

wine --version
wine-3.0

SEE: `https://youtu.be/FlPTLs9NM5s`

```

WINEARCH=win64 WINEPREFIX=/root/.wine64 wine64 connection_patcher.exe Wow.exe
TrinityCore rev. 2ad22015ad45+ 2020-02-03 08:37:38 +0100 (master branch) (Win64, Debug, Static) (connection_patcher)
<Ctrl-C> to stop.


 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Creating patched binary...
Win32 client...
Patching client binary...
patching redirect RSA Modulus
Found offset 7961504
Patching done.
Patching battle.net binary...
patching Portal
Found offset 1714816
patching Bnet
Found offset 878473
patching Signature
Found offset 133625
Patching done.
Base module doesn't exist, downloading it...
Done.
Patching module...
patching Password
Found offset 8776
Patching module finished.
Successfully created your patched binaries.



WINEARCH=win64 WINEPREFIX=/root/.wine64 WINEDEBUG=-all wine64 bnetserver.exe
TrinityCore rev. 2ad22015ad45+ 2020-02-03 08:37:38 +0100 (master branch) (Win64, Debug, Static) (bnetserver)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/LitchLightCore/bnetserver.conf.
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.67.0
Missing name Updates.AutoSetup in config file C:/LitchLightCore/bnetserver.conf, add "Updates.AutoSetup = 1" to this file
Missing name Updates.EnableDatabases in config file C:/LitchLightCore/bnetserver.conf, add "Updates.EnableDatabases = 0" to this file
Automatic database updates are disabled for all databases!
Missing name LoginDatabase.SynchThreads in config file C:/LitchLightCore/bnetserver.conf, add "LoginDatabase.SynchThreads = 1" to this file
Opening DatabasePool '434-auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.1.36-MariaDB
MySQL server ver: 10.1.14-MariaDB 
Connected to MySQL database at 192.168.18.100
MySQL client library: 10.1.36-MariaDB
MySQL server ver: 10.1.14-MariaDB 
Connected to MySQL database at 192.168.18.100
DatabasePool '434-auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Listening on connections from worldservers on port 1118...
Ping MySQL to keep connection alive

```

I must have messed up baaaad somewhere... Ideas welcome!

**Comment by Ovahlord** [comment] 2020-02-04 18:51
What are your client connection settings?

**Comment by DickFiddler** [comment] 2020-02-04 18:55
Many thanks for your input...

```

SET realmlist "192.168.18.101"  <<correct
SET patchlist "localhost"

```

```
id	name	address	localAddress	localSubnetMask	port	icon	flag	timezone	allowedSecurityLevel	population	gamebuild	Region	Battlegroup
1	LitchLight Vanilla 1.12.x	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0
2	LitchLight TBC 2.x.x	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0
3	LitchLight WotLK 3.3.5a	127.0.0.1	127.0.0.1	255.255.255.0	8085	8	2	1	0	0	12340	2	0
4	LitchLight Cata 4.3.4	192.168.18.101	192.168.18.101	255.255.255.0	8085	0	3	1	0	0	15595	2	0
5	LitchLight MoP 5.4.81	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0
6	LitchLight WOD 6.x.x	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0
7	LitchLight Legion 7.10	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0
8	LitchLight BFA 8.x.x	127.0.0.1	127.0.0.1	255.255.255.0	8085	0	1	1	0	0	12340	2	0

```

**Comment by Ovahlord** [comment] 2020-02-04 18:56
It's not correct. You don't use realmlist for Cataclysm anymore. It's SET portal  in the config.wtf now

**Comment by DickFiddler** [comment] 2020-02-04 19:11
Thanks ... different result now ... "Connecting" but no realm list still... that said im still building maps so worldserver cant start yet. Will let u know if I manage to get it sorted.

**Comment by funjoker** [comment] 2020-02-04 20:02
Battle.net_patched.dll need to be named battle.net.dll

can you give us connection log of logs folder?

**Comment by DickFiddler** [comment] 2020-02-04 21:49
@FunJoker ty for the hint ... had not seen the battle.net.dll for 434.

Patched client sits at "Connecting" then finally fails....
SEE: `https://youtu.be/m9Vh5gudWBE`

/mnt/home/USERFILES/WoW/WoW-434/WTF/Config.wtf
```
SET locale "enGB"
SET portal "192.168.18.101"
SET patchlist "localhost"
SET hwDetect "0"
SET enterWorld "1"
SET gxApi "OpenGL"
SET videoOptionsVersion "4"
SET playIntroMovie "4"
SET mouseSpeed "1"
SET Gamma "1.000000"
SET readTOS "1"
SET readEULA "1"
SET readTerminationWithoutNotice "1"
SET showToolsUI "1"
SET accounttype "CT"
SET Sound_EnableAllSound "0"
SET Sound_MusicVolume "0.40000000596046"
SET Sound_AmbienceVolume "0.60000002384186"
SET farclip "185"
SET particleDensity "10"
SET reflectionMode "0"
SET weatherDensity "0"
SET realmName " "
SET gameTip "62"
SET movieSubtitle "1"
SET gxVSync "0"
SET textureFilteringMode "0"
SET checkAddonVersion "0"
SET environmentDetail "50"
SET baseMip "1"
SET gxWindow "1"
SET gxResolution "800x600"
```

/mnt/home/USERFILES/WoW/WoW-434/Data/enGB/realmlist.wtf
```
set portal 192.168.18.101
set patchlist localhost
```

Wow Wine Launch....
```
wine Wow_Patched.exe -opengl
01f1:err:wininet:open_http_connection create_netconn failed: 12029
archive Data/Cache/SoundCache-1.MPQ opened
archive Data/Cache/SoundCache-2.MPQ opened
archive Data/Cache/SoundCache-3.MPQ opened
archive Data/Cache/SoundCache-0.MPQ opened
archive Data/Cache/enGB/SoundCache-enGB.MPQ opened
archive Data/wow-update-base-15211.MPQ opened
archive Data/enGB/wow-update-enGB-15211.MPQ opened
archive Data/Cache/patch-base-15211.MPQ opened
archive Data/Cache/enGB/patch-enGB-15211.MPQ opened
archive Data/Cache/SoundCache-patch-15211.MPQ opened
archive Data/Cache/enGB/SoundCache-patch-enGB-15211.MPQ opened
archive Data/wow-update-base-15354.MPQ opened
archive Data/enGB/wow-update-enGB-15354.MPQ opened
archive Data/Cache/patch-base-15354.MPQ opened
archive Data/Cache/enGB/patch-enGB-15354.MPQ opened
archive Data/Cache/SoundCache-patch-15354.MPQ opened
archive Data/Cache/enGB/SoundCache-patch-enGB-15354.MPQ opened
archive Data/wow-update-base-15595.MPQ opened
archive Data/enGB/wow-update-enGB-15595.MPQ opened
archive Data/Cache/patch-base-15595.MPQ opened
archive Data/Cache/enGB/patch-enGB-15595.MPQ opened
archive Data/Cache/SoundCache-patch-15595.MPQ opened
archive Data/Cache/enGB/SoundCache-patch-enGB-15595.MPQ opened
archive Data\world2.MPQ opened
archive Data\enGB\expansion3-speech-enGB.MPQ opened
archive Data\enGB\expansion3-locale-enGB.MPQ opened
archive Data\expansion3.MPQ opened
archive Data\enGB\expansion2-speech-enGB.MPQ opened
archive Data\enGB\expansion2-locale-enGB.MPQ opened
archive Data\expansion2.MPQ opened
archive Data\enGB\expansion1-speech-enGB.MPQ opened
archive Data\enGB\expansion1-locale-enGB.MPQ opened
archive Data\expansion1.MPQ opened
archive Data\enGB\speech-enGB.MPQ opened
archive Data\enGB\locale-enGB.MPQ opened
archive Data\sound.MPQ opened
archive Data\world.MPQ opened
archive Data\art.MPQ opened
01e4:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
01e4:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33f658,0x00000000), stub!
01e4:fixme:dxgi:DXGID3D10CreateDevice Ignoring flags 0x1.
01e4:fixme:dxgi:dxgi_check_feature_level_support Ignoring adapter type.
01e4:fixme:dxgi:dxgi_device_init Ignoring adapter type.
01e4:fixme:d3d11:device_parent_create_swapchain_texture device_parent 0x127b5c, container_parent 0x127d98, wined3d_desc 0x33f6f8, texture flags 0, wined3d_texture 0x154720 partial stub!
01e4:fixme:d3d11:device_parent_create_swapchain_texture Implement DXGI<->wined3d usage conversion.
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33ed78,0x00000000), stub!
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33ecb8,0x00000000), stub!
01e4:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
01e4:err:wgl:X11DRV_wglCreateContextAttribsARB Context creation failed (error 1)
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33f2c8,0x00000000), stub!
01e4:fixme:dxgi:dxgi_check_feature_level_support Ignoring adapter type.
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33f068,0x00000000), stub!
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33ef98,0x00000000), stub!
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33f048,0x00000000), stub!
01e4:fixme:win:EnumDisplayDevicesW ((null),0,0x33ef78,0x00000000), stub!
01e4:fixme:imm:ImmReleaseContext (0x290320, 0x12b5d8): stub

```

Bnet.log ...
```
TrinityCore rev. 2ad22015ad45+ 2020-02-03 08:37:38 +0100 (master branch) (Win64, Debug, Static) (bnetserver)
<Ctrl-C> to stop.

 ______                       __
/\__  _\       __          __/\ \__
\/_/\ \/ _ __ /\_\    ___ /\_\ \, _\  __  __
   \ \ \/\`'__\/\ \ /' _ `\/\ \ \ \/ /\ \/\ \
    \ \ \ \ \/ \ \ \/\ \/\ \ \ \ \ \_\ \ \_\ \
     \ \_\ \_\  \ \_\ \_\ \_\ \_\ \__\\/`____ \
      \/_/\/_/   \/_/\/_/\/_/\/_/\/__/ `/___/> \
                                 C O R E  /\___/
http://TrinityCore.org                    \/__/

Using configuration file C:/LitchLightCore/bnetserver.conf.
Using SSL version: OpenSSL 1.0.2l  25 May 2017 (library: OpenSSL 1.0.2l  25 May 2017)
Using Boost version: 1.67.0
Missing name Updates.AutoSetup in config file C:/LitchLightCore/bnetserver.conf, add "Updates.AutoSetup = 1" to this file
Missing name Updates.EnableDatabases in config file C:/LitchLightCore/bnetserver.conf, add "Updates.EnableDatabases = 0" to this file
Automatic database updates are disabled for all databases!
Missing name LoginDatabase.SynchThreads in config file C:/LitchLightCore/bnetserver.conf, add "LoginDatabase.SynchThreads = 1" to this file
Opening DatabasePool '434-auth'. Asynchronous connections: 1, synchronous connections: 1.
MySQL client library: 10.1.36-MariaDB
MySQL server ver: 10.1.14-MariaDB 
Connected to MySQL database at 192.168.18.100
MySQL client library: 10.1.36-MariaDB
MySQL server ver: 10.1.14-MariaDB 
Connected to MySQL database at 192.168.18.100
DatabasePool '434-auth' opened successfully. 2 total connections running.
Started auth database connection pool.
Listening on connections from worldservers on port 1118...
```
Sorry guys ... it's bound to be my side that is the problem eg. missed something basic!

**Comment by Ovahlord** [comment] 2020-02-04 21:57
Dude, you need to create battle.net accounts.   bnetaccount user@name password. Grunt login is gone. You have to do e-mail logins

**Comment by DickFiddler** [comment] 2020-02-04 22:09
SEE: `https://youtu.be/-x_DAjDRWrY`

Still Failing ... Doh!

Many thanks for the help ... still failing atm but i have not created a bnet account (world server still setting up).

Will try again later.

 : )

**Comment by funjoker** [comment] 2020-02-04 22:11
delete realmlist.wtf
give us connection.log
use bnet account

**Comment by DickFiddler** [comment] 2020-02-04 22:36
@funjoker ... 
realmlist.wtf = deleted
connection.log ^^ as above (you mean the bnetserver log Bnet.log?) shows no activity.

bnetserver.conf...
```
###############################################
# Trinity Core Auth Server configuration file #
###############################################
[bnetserver]

###################################################################################################
# SECTION INDEX
#
#    EXAMPLE CONFIG
#    AUTH SERVER SETTINGS
#    MYSQL SETTINGS
#    LOGGING SYSTEM SETTINGS
#
###################################################################################################

###################################################################################################
# EXAMPLE CONFIG
#
#    Variable
#        Description: Brief description what the variable is doing.
#        Important:   Annotation for important things about this variable.
#        Example:     "Example, i.e. if the value is a string"
#        Default:     10 - (Enabled|Comment|Variable name in case of grouped config options)
#                     0  - (Disabled|Comment|Variable name in case of grouped config options)
#
# Note to developers:
# - Copy this example to keep the formatting.
# - Line breaks should be at column 100.
###################################################################################################

###################################################################################################
# AUTH SERVER SETTINGS
#
#    LogsDir
#        Description: Logs directory setting.
#        Important:   LogsDir needs to be quoted, as the string might contain space characters.
#                     Logs directory must exists, or log file creation will be disabled.
#        Default:     "" - (Log files will be stored in the current path)

LogsDir = ""

#
#    MaxPingTime
#        Description: Time (in minutes) between database pings.
#        Default:     30

MaxPingTime = 30

#
#    WorldserverListenPort
#        Description: TCP port to listen on for incoming worldserver IPC.
#        Default:     1118

WorldserverListenPort = 1118

#
#    BattlenetPort
#        Description: TCP port to reach the auth server for battle.net connections.
#        Default:     1119

BattlenetPort = 1119

#
#
#    BindIP
#        Description: Bind auth server to IP/hostname
#        Default:     "0.0.0.0" - (Bind to all IPs on the system)

BindIP = "192.168.18.101"

#
#    PidFile
#        Description: Auth server PID file.
#        Example:     "./bnetserver.pid"  - (Enabled)
#        Default:     ""                  - (Disabled)

PidFile = ""

#
#    UseProcessors
#        Description: Processors mask for Windows and Linux based multi-processor systems.
#        Example:     A computer with 2 CPUs:
#                     1 - 1st CPU only, 2 - 2nd CPU only, 3 - 1st and 2nd CPU, because 1 | 2 is 3
#        Default:     0  - (Selected by OS)
#                     1+ - (Bit mask value of selected processors)

UseProcessors = 0

#
#    ProcessPriority
#        Description: Process priority setting for Windows and Linux based systems.
#        Details:     On Linux, a nice value of -15 is used. (requires superuser). On Windows, process is set to HIGH class.
#        Default:     0 - (Normal)
#                     1 - (High)

ProcessPriority = 0

#
#    RealmsStateUpdateDelay
#        Description: Time (in seconds) between realm list updates.
#        Default:     10
#                     0  - (Disabled)

RealmsStateUpdateDelay = 10

#
#    WrongPass.MaxCount
#        Description: Number of login attemps with wrong password before the account or IP will be
#                     banned.
#        Default:     0  - (Disabled)
#                     1+ - (Enabled)

WrongPass.MaxCount = 0

#
#    WrongPass.BanTime
#        Description: Time (in seconds) for banning account or IP for invalid login attempts.
#        Default:     600 - (10 minutes)
#                     0   - (Permanent ban)

WrongPass.BanTime = 600

#
#    WrongPass.BanType
#        Description: Ban type for invalid login attempts.
#        Default:     0 - (Ban IP)
#                     1 - (Ban Account)

WrongPass.BanType = 0

#
###################################################################################################

###################################################################################################
# MYSQL SETTINGS
#
#    LoginDatabaseInfo
#        Description: Database connection settings for the realm server.
#        Example:     "hostname;port;username;password;database"
#                     ".;somenumber;username;password;database" - (Use named pipes on Windows
#                                                                 "enable-named-pipe" to [mysqld]
#                                                                 section my.ini)
#                     ".;/path/to/unix_socket;username;password;database" - (use Unix sockets on
#                                                                           Unix/Linux)
#        Default:     "127.0.0.1;3306;trinity;trinity;auth"

LoginDatabaseInfo = "192.168.18.100;3310;trinity;trinity;434-auth"

#
#    LoginDatabase.WorkerThreads
#        Description: The amount of worker threads spawned to handle asynchronous (delayed) MySQL
#                     statements. Each worker thread is mirrored with its own connection to the
#        Default:     1

LoginDatabase.WorkerThreads = 1

#
#    Wrong.Password.Login.Logging
#        Description: Additionally log attempted wrong password logging
#        Default:     0 - (Disabled)
#                     1 - (Enabled)

Wrong.Password.Login.Logging = 1
#
###################################################################################################

###################################################################################################
#
#  LOGGING SYSTEM SETTINGS
#
#  Appender config values: Given a appender "name"
#    Appender.name
#        Description: Defines 'where to log'
#        Format:      Type,LogLevel,Flags,optional1,optional2,optional3
#
#                     Type
#                         0 - (None)
#                         1 - (Console)
#                         2 - (File)
#                         3 - (DB)
#
#                     LogLevel
#                         0 - (Disabled)
#                         1 - (Trace)
#                         2 - (Debug)
#                         3 - (Info)
#                         4 - (Warn)
#                         5 - (Error)
#                         6 - (Fatal)
#
#                     Flags:
#                         0 - None
#                         1 - Prefix Timestamp to the text
#                         2 - Prefix Log Level to the text
#                         4 - Prefix Log Filter type to the text
#                         8 - Append timestamp to the log file name. Format: YYYY-MM-DD_HH-MM-SS (Only used with Type = 2)
#                        16 - Make a backup of existing file before overwrite (Only used with Mode = w)
#
#                     Colors (read as optional1 if Type = Console)
#                         Format: "fatal error warn info debug trace"
#                         0 - BLACK
#                         1 - RED
#                         2 - GREEN
#                         3 - BROWN
#                         4 - BLUE
#                         5 - MAGENTA
#                         6 - CYAN
#                         7 - GREY
#                         8 - YELLOW
#                         9 - LRED
#                        10 - LGREEN
#                        11 - LBLUE
#                        12 - LMAGENTA
#                        13 - LCYAN
#                        14 - WHITE
#                         Example: "13 11 9 5 3 1"
#
#                     File: Name of the file (read as optional1 if Type = File)
#                         Allows to use one "%s" to create dynamic files
#
#                     Mode: Mode to open the file (read as optional2 if Type = File)
#                          a - (Append)
#                          w - (Overwrite)
#
#                     MaxFileSize: Maximum file size of the log file before creating a new log file
#                     (read as optional3 if Type = File)
#                         Size is measured in bytes expressed in a 64-bit unsigned integer.
#                         Maximum value is 4294967295 (4 gb). Leave blank for no limit.
#                         NOTE: Does not work with dynamic filenames.
#                         Example:  536870912 (512 mb)
#

Appender.Console=1,1,0
Appender.Bnet=2,2,0,Bnet.log,w

#  Logger config values: Given a logger "name"
#    Logger.name
#        Description: Defines 'What to log'
#        Format:      LogLevel,AppenderList
#
#                     LogLevel
#                         0 - (Disabled)
#                         1 - (Trace)
#                         2 - (Debug)
#                         3 - (Info)
#                         4 - (Warn)
#                         5 - (Error)
#                         6 - (Fatal)
#
#                     AppenderList: List of appenders linked to logger
#                     (Using spaces as separator).
#

Logger.root=3,Console Bnet
Logger.realmlist=3,Console Bnet
Logger.session=3,Console Bnet
Logger.session.packets=3,Console Bnet

#
###################################################################################################

SourceDirectory  = "C:/LitchLightCore/Source"

```

**Comment by funjoker** [comment] 2020-02-04 22:50
i mean of wow client

**Comment by Ghaster** [comment] 2020-02-04 22:52
Try running this on the auth database:
```
UPDATE `battlenet_components` SET `Build`=1807 WHERE `Program`='Tool' AND `Platform`='Win';
```

**Comment by DickFiddler** [comment] 2020-02-04 23:06
@Ghaster ... executed that query ... restarted the server and client  ... no change!
Table now looks like this:
```
Program	Platform	Build
Bnet	Cmp1	3
Bnet	Mac	26487
Bnet	Mc64	26487
Bnet	Win	26487
Bnet	Wn64	26487
Tool	Mac	0
Tool	Mc64	0
Tool	Win	1807
Tool	Wn64	0
WoW	base	15595
WoW	enCN	15595
WoW	enGB	15595
WoW	enTW	15595
WoW	enUS	15595
WoW	koKR	15595
WoW	Mac	15595
WoW	Mc64	15595
WoW	Win	15595
WoW	Wn64	15595
```

@funjoker ... thanks for explaination ... Client connection.log
```
2/4 22:24:33.538  Login program=WoW platform=Win locale=enGB
2/4 22:24:33.586  Component WoW.Win.15595
2/4 22:24:33.627  Component WoW.base.15595
2/4 22:24:33.660  Component WoW.enGB.15595
2/4 22:24:33.694  Component Tool.Win.0
2/4 22:24:34.102  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/4 22:24:34.158  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
2/4 22:28:12.036  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/4 22:28:31.672  Login program=WoW platform=Win locale=enGB
2/4 22:28:31.706  Component WoW.Win.15595
2/4 22:28:31.739  Component WoW.base.15595
2/4 22:28:31.772  Component WoW.enGB.15595
2/4 22:28:31.806  Component Tool.Win.0
2/4 22:28:31.868  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/4 22:28:31.905  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
2/4 22:36:04.943  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/4 22:36:04.986  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
2/4 22:36:35.306  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
2/4 22:36:35.351  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED 
```

**Comment by funjoker** [comment] 2020-02-04 23:59
This issue is caused by missing/incorrect .auth files
Since i have no idea how linux works with mono etc i can't directly help you.
On Windows these auth files are at `C:\ProgramData\Blizzard Entertainment\Battle.net\Cache`
For 4.3.4 TC you need these files (created by patcher):

`C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\0a\3a\0a3afee2cade3a0e8b458c4b4660104cac7fc50e2ca9bef0d708942e77f15c1d.auth`

`C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\2e\6D\2E6D53ADAB37A41542B38E01F62CD365EAB8805ED0DE73C307CC6D9D1DFE478C.auth`

`C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\8f\52\8f52906a2c85b416a595702251570f96d3522f39237603115f2f1ab24962043c.auth`

`C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\85\1C\851C1D2EF926E9B9A345A460874E65517195129B9E3BDEC7CC77710FA0B1FAD6.auth`

**Comment by DickFiddler** [comment] 2020-02-05 00:11
Thanks FunJoker... Server and client are runing under WINE and have native windows runtimes (VC and .net) - no mono.

```
PRESENT:

C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\2e\6D\2E6D53ADAB37A41542B38E01F62CD365EAB8805ED0DE73C307CC6D9D1DFE478C.auth

C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\8f\52\8f52906a2c85b416a595702251570f96d3522f39237603115f2f1ab24962043c.auth

```

```
MISSING
C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\0a\3a\0a3afee2cade3a0e8b458c4b4660104cac7fc50e2ca9bef0d708942e77f15c1d.auth

C:\ProgramData\Blizzard Entertainment\Battle.net\Cache\85\1C\851C1D2EF926E9B9A345A460874E65517195129B9E3BDEC7CC77710FA0B1FAD6.auth
```

**Comment by funjoker** [comment] 2020-02-05 00:15
try to get clean exes and patch them again, (both 86 and 64)
Rename _patched.whatever to correct namings.
Use Portal not realmlist
delete realmlist if exists

**Comment by DickFiddler** [comment] 2020-02-05 00:21
Will do ... the 434 client I have here does not have a 64bit .exe so will look for one.
If anyone can post their .auth files I would like to try them in the meantime ... they are ok to transfer from one install to another?

**Comment by funjoker** [comment] 2020-02-05 00:37
64bit is available from blizzard forum just google

**Comment by Ghaster** [comment] 2020-02-05 00:50
Oh your build for tools was previously 2736?
Try this query then, it should then match your components from connection.log:
```
UPDATE `battlenet_components` SET `Build`=0 WHERE `Program`='Tool' AND `Platform`='Win';
```
That "Unable to connect" is sometimes caused by a mismatch of modules build defined in server and client.

**Comment by DickFiddler** [comment] 2020-02-05 01:07
@Ghaster ... hehe SET `Build`=0 seems to have worked in conjunction with clientpatcher for 64 bits and of course running the 64 bit wow client from the blizz forum (ty @funjoker!).

I am now seing "Details Incorrect" which means it has at least checked a password!

Funny how a fail can be a triumph in WoW!

Will let you know how it goes when I manage to get maps vmaps etc extracted.

Huge thanks to you all.

The Fiddler.
<3

**Comment by Ovahlord** [comment] 2020-02-05 19:03
Anyways, this is not an core issue, this is an user issue, so yeah. Closing that one.

**Closed by Ovahlord** 2020-02-05 19:03 UTC
